title: Practitioner's Guides by Scott Logic
about: "The Scott Logic practitioner's guides are designed to be
small practical guides for IT professionals. We draw on our collective
experience to tackle topics that we don't feel are addressed elsewhere.
Our hope is that these little 'value adds' will help you just as much as
they have helped us."

baseurl: "/practitioners-guides"
url: "https://scottlogic.github.io"
sl_url: "https://www.scottlogic.com"
GitHub_url: "https://github.com/ScottLogic/practitioners-guides"

markdown: GFM
theme: null
plugins:
  - jekyll-toc

toc:
  enabled: true
  h_min: 1
  h_max: 3

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:collection/:path/
    sort_by: date

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
